// precompute_layout.mjs - build-time layout precompute.
//
// Runs the scene layout engine once per scene at the canonical 16:9 frame
// (1920x1080) and emits generated/precomputed_layout.ts as a map keyed by
// scene_name, each entry holding { final: ComputedItem[] }. The browser loads
// these positions instead of recomputing layout at runtime.
//
// Why fixed 16:9 is a valid precompute: parity testing confirmed exact agreement
// between running the engine at canonical 16:9 and at a live 16:9 panel (see
// docs/active_plans/reports/m0_layout_parity_16x9.md and
// tests/e2e/e2e_layout_parity_16x9.mjs). The only viewport-dependent term in
// the engine is viewportAspect = viewport.w / viewport.h, identical for every
// 16:9 viewport, so the canonical frame reproduces the live layout exactly.
//
// This script depends only on the stable runPipeline(scene, {library, assets,
// viewport}) signature, so it stays correct as engine internals change.
//
// Run:
//   node --import tsx pipeline/precompute_layout.mjs
// Or via the production build (build_github_pages.sh, after build_generated.sh).

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

import { runPipeline } from "../src/scene_runtime/layout/index.ts";
import { SCENES } from "../generated/scenes.js";
import { OBJECT_LIBRARY, ASSET_SPECS } from "../generated/object_library.js";

// Canonical compiled layout contract. 1920x1080 is the engine DEFAULT_VIEWPORT
// and the 16:9 frame the production app letterboxes #scene-root to. Parity
// testing confirms any 16:9 viewport yields the identical ComputedItem[].
const PRECOMPUTE_VIEWPORT = { w: 1920, h: 1080 };

//============================================
// Repo root and output path
//============================================

// Resolve the repo root from git so the output path does not depend on the
// current working directory (repo style: never derive paths from cwd).
function repo_root() {
  const top = execFileSync("git", ["rev-parse", "--show-toplevel"], {
    encoding: "utf8",
  });
  return top.trim();
}

//============================================
// Run the engine for one scene
//============================================

// Run the engine for one scene at the canonical 16:9 frame and return its
// final ComputedItem[]. This is the exact call the runtime renderer makes,
// differing only in the fixed viewport argument.
function run_scene(scene) {
  const result = runPipeline(scene, {
    library: OBJECT_LIBRARY,
    assets: ASSET_SPECS,
    viewport: PRECOMPUTE_VIEWPORT,
  });
  return result.final;
}

// Stable serialization order: sort items by placement_name so the emitted file
// never depends on map/zone iteration order. The engine already orders final[]
// by zone then placement; sorting here makes the order explicit and deterministic.
function sort_items(items) {
  const copy = [...items];
  copy.sort((a, b) => {
    if (a.placement_name < b.placement_name) return -1;
    if (a.placement_name > b.placement_name) return 1;
    return 0;
  });
  return copy;
}

//============================================
// Emit the generated TypeScript artifact
//============================================

// Build the generated/precomputed_layout.ts text. Scenes are emitted in sorted
// key order, and each scene's items are sorted by placement_name, so two builds
// of the same source produce a byte-identical file (the determinism contract).
function build_artifact(layout_by_scene) {
  const scene_names = Object.keys(layout_by_scene).sort();
  let body = "";
  body += "// AUTO-GENERATED by pipeline/precompute_layout.mjs. Do not edit by hand.\n";
  body += "//\n";
  body += "// Build-time layout: runPipeline output for every scene at the canonical\n";
  body += "// 16:9 frame (" + PRECOMPUTE_VIEWPORT.w + "x" + PRECOMPUTE_VIEWPORT.h + ").\n";
  body += "// Keyed by scene_name; each entry holds { final: ComputedItem[] }.\n";
  body += "\n";
  body += "import type { ComputedItem } from '../src/scene_runtime/layout/types.js';\n";
  body += "\n";
  body += "export interface PrecomputedSceneLayout {\n";
  body += "\tfinal: ComputedItem[];\n";
  body += "}\n";
  body += "\n";
  body += "export const PRECOMPUTED_LAYOUT: Record<string, PrecomputedSceneLayout> = ";
  // Assemble the keyed map as deterministic JSON. ComputedItem is plain data
  // (primitives, string arrays, optional flags), so JSON round-trips it exactly.
  const ordered = {};
  for (const name of scene_names) {
    ordered[name] = { final: layout_by_scene[name] };
  }
  body += JSON.stringify(ordered, null, "\t");
  body += ";\n";
  return body;
}

//============================================
// Main
//============================================

function main() {
  const root = repo_root();
  const out_path = path.join(root, "generated", "precomputed_layout.ts");

  const scene_names = Object.keys(SCENES).sort();
  const layout_by_scene = {};
  for (const name of scene_names) {
    const scene = SCENES[name];
    layout_by_scene[name] = sort_items(run_scene(scene));
  }

  const text = build_artifact(layout_by_scene);
  fs.writeFileSync(out_path, text, "utf8");

  // Report what was emitted so the build log records scene coverage.
  process.stdout.write(
    "precompute_layout: emitted " +
      scene_names.length +
      " scenes to generated/precomputed_layout.ts " +
      "(viewport " +
      PRECOMPUTE_VIEWPORT.w +
      "x" +
      PRECOMPUTE_VIEWPORT.h +
      ")\n",
  );
}

main();
