"""Confusion-table runner for scene lint Group B rules.

Loads a labeled corpus (positive and negative ground-truth labels),
matches labels against Finding output, and computes per-rule
TP / FP / FN / TN counts plus precision and recall.

Corpus schema (YAML file with a top-level 'labels' list):

  Positive label (rule SHOULD fire):
    label_type: positive
    scene: <scene_name>
    placement_name: <placement_name>
    precheck_kind: <precheck failure kind, free text>
    mapped_rule: <rule name, e.g. B1>
    reviewer: <reviewer name>
    reviewed_at: <YYYY-MM-DD>

  Negative label (rule SHOULD NOT fire):
    label_type: negative
    scene: <scene_name>
    placement_name: <placement_name>
    candidate_rule: <rule name>
    reviewer: <reviewer name>
    reviewed_at: <YYYY-MM-DD>
    rationale: <why the rule should not fire here>

If the corpus file does not exist or is empty, both functions treat it as
an empty corpus (no labels), so callers do not crash on a missing file.
"""

from pathlib import Path
from typing import Any

import yaml

from validation.scene_lint.findings import Finding


#============================================
# Required fields per label type
#============================================

POSITIVE_REQUIRED_FIELDS = frozenset({
	'label_type',
	'scene',
	'placement_name',
	'precheck_kind',
	'mapped_rule',
	'reviewer',
	'reviewed_at',
})

NEGATIVE_REQUIRED_FIELDS = frozenset({
	'label_type',
	'scene',
	'placement_name',
	'candidate_rule',
	'reviewer',
	'reviewed_at',
	'rationale',
})


#============================================
# Corpus loader
#============================================

def load_labeled_corpus(path: Path) -> dict[str, Any]:
	"""Load a labeled corpus YAML file into a structured dict.

	Returns a dict with keys:
	  'positives': list of positive label dicts
	  'negatives': list of negative label dicts
	  'source': str, the file path as a string

	If the file does not exist or is empty, returns an empty corpus:
	  {'positives': [], 'negatives': [], 'source': str(path)}

	Raises:
	  ValueError: if any label entry is missing a required field.
	  RuntimeError: if the YAML is structurally invalid (not a dict with 'labels' list).
	"""
	# Treat missing file as empty corpus per scope boundaries
	if not path.exists():
		return {'positives': [], 'negatives': [], 'source': str(path)}

	raw_text = path.read_text(encoding='utf-8').strip()
	if not raw_text:
		return {'positives': [], 'negatives': [], 'source': str(path)}

	data = yaml.safe_load(raw_text)
	if data is None:
		return {'positives': [], 'negatives': [], 'source': str(path)}

	if not isinstance(data, dict):
		raise RuntimeError(f'Corpus file must be a YAML mapping at top level: {path}')
	# Accept both 'labels' and 'entries' as the top-level list key.
	# 'labels' is the canonical schema; 'entries' is the key used in the
	# auto-seeded labeled_corpus.yaml generated by WP-B-RULES-4.
	if 'labels' in data:
		raw_list = data['labels']
	elif 'entries' in data:
		raw_list = data['entries']
	else:
		raise RuntimeError(
			f"Corpus file missing required 'labels' (or 'entries') key: {path}"
		)
	if not isinstance(raw_list, list):
		raise RuntimeError(f"Corpus label list must be a list: {path}")

	positives: list[dict[str, Any]] = []
	negatives: list[dict[str, Any]] = []

	for i, entry in enumerate(raw_list):
		if not isinstance(entry, dict):
			raise ValueError(f'Corpus label entry {i} is not a mapping: {entry!r}')

		# Determine label type to pick the right required-field set
		label_type = entry.get('label_type')
		if label_type == 'positive':
			required = POSITIVE_REQUIRED_FIELDS
		elif label_type == 'negative':
			required = NEGATIVE_REQUIRED_FIELDS
		else:
			raise ValueError(
				f"Corpus label entry {i} has unknown or missing label_type: {label_type!r}. "
				"Must be 'positive' or 'negative'."
			)

		# Raise on missing required fields per PYTHON_STYLE.md "do not hide bugs with defaults"
		missing = required - set(entry.keys())
		if missing:
			raise ValueError(
				f'Corpus label entry {i} (label_type={label_type!r}) missing required fields: '
				f'{sorted(missing)}'
			)

		if label_type == 'positive':
			positives.append(entry)
		else:
			negatives.append(entry)

	corpus = {
		'positives': positives,
		'negatives': negatives,
		'source': str(path),
	}
	return corpus


#============================================
# Confusion math
#============================================

def compute_confusion(
	findings: list[Finding],
	corpus: dict[str, Any],
	rule_name: str,
) -> dict[str, Any]:
	"""Compute TP/FP/FN/TN confusion counts for a single rule.

	Matching rules:
	  - TP: positive label (scene, placement_name, mapped_rule == rule_name)
	        that has a matching finding (scene, placement_name, rule == rule_name).
	  - FN: positive label for rule_name that has no matching finding.
	  - FP: negative label (scene, placement_name, candidate_rule == rule_name)
	        that DOES have a matching finding (rule fired when it should not have).
	  - TN: negative label for rule_name that has no matching finding (rule correctly silent).

	Args:
	  findings: All findings from the scene lint run (any rules).
	  corpus: Loaded corpus dict from load_labeled_corpus().
	  rule_name: The rule to evaluate (e.g., 'B1', 'aspect_distorted_predicted').

	Returns:
	  Dict with keys:
	    tp, fp, fn, tn: int counts
	    precision: float in [0.0, 1.0] or None if tp + fp == 0
	    recall: float in [0.0, 1.0] or None if tp + fn == 0
	    positive_count: int number of positive labels for this rule
	"""
	# Build a set of (scene, placement_name) pairs where the rule fired
	fired_keys: set[tuple[str, str | None]] = set()
	for f in findings:
		if f.rule == rule_name:
			fired_keys.add((f.scene, f.placement_name))

	# Evaluate positive labels for this rule
	positive_labels = [
		p for p in corpus['positives']
		if p['mapped_rule'] == rule_name
	]
	tp = 0
	fn = 0
	for label in positive_labels:
		key = (label['scene'], label['placement_name'])
		if key in fired_keys:
			tp += 1
		else:
			fn += 1

	# Evaluate negative labels for this rule
	negative_labels = [
		n for n in corpus['negatives']
		if n['candidate_rule'] == rule_name
	]
	fp = 0
	tn = 0
	for label in negative_labels:
		key = (label['scene'], label['placement_name'])
		if key in fired_keys:
			fp += 1
		else:
			tn += 1

	# Precision = TP / (TP + FP); None if denominator is zero
	precision: float | None
	if tp + fp > 0:
		precision = tp / (tp + fp)
	else:
		precision = None

	# Recall = TP / (TP + FN); None if denominator is zero
	recall: float | None
	if tp + fn > 0:
		recall = tp / (tp + fn)
	else:
		recall = None

	stats = {
		'tp': tp,
		'fp': fp,
		'fn': fn,
		'tn': tn,
		'precision': precision,
		'recall': recall,
		'positive_count': len(positive_labels),
	}
	return stats


#============================================
# Markdown writer
#============================================

def write_confusion_markdown(
	stats: dict[str, Any],
	rule_name: str,
	corpus: dict[str, Any],
	out_path: Path,
) -> None:
	"""Write a per-rule confusion-table report to a Markdown file.

	Args:
	  stats: Dict returned by compute_confusion().
	  rule_name: The rule name being reported (e.g., 'B1').
	  corpus: Loaded corpus dict (used for source and reviewer info).
	  out_path: Destination Markdown file path.
	"""
	tp = stats['tp']
	fp = stats['fp']
	fn = stats['fn']
	tn = stats['tn']
	precision = stats['precision']
	recall = stats['recall']
	positive_count = stats['positive_count']
	source = corpus['source']

	# Format precision and recall for display
	if precision is None:
		precision_str = 'N/A (no positive or FP findings)'
	else:
		precision_str = f'{precision:.3f}'

	if recall is None:
		recall_str = 'N/A (no positive labels)'
	else:
		recall_str = f'{recall:.3f}'

	# Collect unique reviewers from corpus
	reviewers: list[str] = []
	for label in corpus['positives'] + corpus['negatives']:
		reviewer = label.get('reviewer', '')
		if reviewer and reviewer not in reviewers:
			reviewers.append(reviewer)
	reviewer_str = ', '.join(sorted(reviewers)) if reviewers else 'none listed'

	lines: list[str] = []
	lines.append(f'# Confusion table: {rule_name}\n')
	lines.append('\n')
	lines.append(f'Corpus: `{source}`\n')
	lines.append(f'Reviewers: {reviewer_str}\n')
	lines.append(f'Positive labels (ground truth): {positive_count}\n')
	lines.append('\n')
	lines.append('## Counts\n')
	lines.append('\n')
	lines.append('| Metric | Value |\n')
	lines.append('| --- | --- |\n')
	lines.append(f'| True Positives (TP) | {tp} |\n')
	lines.append(f'| False Positives (FP) | {fp} |\n')
	lines.append(f'| False Negatives (FN) | {fn} |\n')
	lines.append(f'| True Negatives (TN) | {tn} |\n')
	lines.append('\n')
	lines.append('## Metrics\n')
	lines.append('\n')
	lines.append('| Metric | Value |\n')
	lines.append('| --- | --- |\n')
	lines.append(f'| Precision | {precision_str} |\n')
	lines.append(f'| Recall | {recall_str} |\n')
	lines.append('\n')

	out_path.write_text(''.join(lines), encoding='utf-8')
