// AUTO-GENERATED by tools/build_protocol_data.py from content/tutorial_hemocytometer_count/*.yaml. DO NOT EDIT BY HAND.

export interface InventoryItem {
	label: string;
	role: string;
	scene: string;
	asset?: string;
	liquidCapable?: boolean;
	capacityMl?: number;
	allowedLiquids?: string[];
	contains?: string;
	containsAny?: string[];
	visualOnly?: boolean;
}

export interface InventoryReagent {
	label: string;
	colorKey: string;
	displayColor: string;
}

export const EQUIPMENT: Record<string, InventoryItem> = {
	hemocytometer: { asset: "hemocytometer", label: "Hemocytometer", role: "instrument", scene: "bench" },
	microscope: { asset: "microscope", label: "Microscope", role: "instrument", scene: "bench" },
	cell_culture_dish: { asset: "cell_culture_dish", label: "Cell Culture Dish", role: "culture_vessel", scene: "hood" },
};

export const REAGENTS: Record<string, InventoryReagent> = {
};
