// AUTO-GENERATED by tools/build_protocol_data.py from content/<protocol>/*.yaml. DO NOT EDIT BY HAND.

export interface InventoryItem {
	label: string;
	role: string;
	scene: string;
	asset?: string;
	liquidCapable?: boolean;
	capacityMl?: number;
	allowedLiquids?: string[];
	contains?: string;
	containsAny?: string[];
	visualOnly?: boolean;
}

export interface InventoryReagent {
	label: string;
	colorKey: string;
	displayColor: string;
}

export const EQUIPMENT: Record<string, InventoryItem> = {
	serological_pipette: { allowedLiquids: [ "media", "pbs", "trypsin", "cells" ], asset: "sero_pipette", capacityMl: 10, label: "Serological pipette", liquidCapable: true, role: "transfer_tool", scene: "hood" },
	aspirating_pipette: { allowedLiquids: [ "media" ], asset: "aspirating_pipette", capacityMl: 10, label: "Aspirating pipette", liquidCapable: true, role: "aspirate_tool", scene: "hood" },
	multichannel_pipette: { allowedLiquids: [ "media", "mtt", "dmso" ], asset: "multichannel_pipette", capacityMl: 300, label: "Multichannel pipette", liquidCapable: true, role: "transfer_tool", scene: "hood" },
	flask: { allowedLiquids: [ "media", "trypsin", "cells" ], asset: "t75_flask", capacityMl: 20, label: "T-75 Flask", liquidCapable: true, role: "cell_container", scene: "hood" },
	well_plate: { allowedLiquids: [ "media", "cells", "mtt", "dmso", "carboplatin", "metformin" ], asset: "well_plate_24", capacityMl: 1, label: "24-Well Plate", liquidCapable: true, role: "culture_vessel", scene: "hood" },
	media_bottle: { allowedLiquids: [ "media" ], asset: "media_bottle", capacityMl: 500, contains: "media", label: "Complete media", liquidCapable: true, role: "reagent_source", scene: "hood" },
	pbs_bottle: { allowedLiquids: [ "pbs" ], asset: "pbs_bottle", capacityMl: 500, contains: "pbs", label: "1x PBS", liquidCapable: true, role: "reagent_source", scene: "hood" },
	trypsin_bottle: { allowedLiquids: [ "trypsin" ], asset: "media_bottle", capacityMl: 500, contains: "trypsin", label: "Trypsin-EDTA", liquidCapable: true, role: "reagent_source", scene: "hood" },
	ethanol_bottle: { allowedLiquids: [ "ethanol" ], asset: "ethanol_spray", capacityMl: 500, contains: "ethanol", label: "70% Ethanol", liquidCapable: true, role: "reagent_source", scene: "hood" },
	sterile_water: { allowedLiquids: [ "water" ], asset: "media_bottle", capacityMl: 500, contains: "water", label: "Sterile Water", liquidCapable: true, role: "reagent_source", scene: "hood" },
	dmso_bottle: { allowedLiquids: [ "dmso" ], asset: "media_bottle", capacityMl: 500, contains: "dmso", label: "DMSO", liquidCapable: true, role: "reagent_source", scene: "hood" },
	mtt_vial: { allowedLiquids: [ "mtt" ], asset: "media_bottle", capacityMl: 500, contains: "mtt", label: "MTT 5 mg/mL", liquidCapable: true, role: "modal_tool", scene: "hood" },
	carboplatin_stock: { allowedLiquids: [ "carboplatin" ], asset: "media_bottle", capacityMl: 500, contains: "carboplatin", label: "Carboplatin 10 mM", liquidCapable: true, role: "reagent_source", scene: "hood" },
	metformin_stock: { allowedLiquids: [ "metformin" ], asset: "media_bottle", capacityMl: 500, contains: "metformin", label: "Metformin 1 M", liquidCapable: true, role: "reagent_source", scene: "hood" },
	micropipette_rack: { asset: "micropipette_rack", label: "P20/P200/P1000", role: "decoration", scene: "hood", visualOnly: true },
	drug_vials: { asset: "drug_vial_rack", label: "Drug Dilutions", role: "decoration", scene: "hood", visualOnly: true },
	conical_15ml_rack: { asset: "conical_15ml_rack", label: "15 mL Tubes", role: "decoration", scene: "hood", visualOnly: true },
	dilution_tube_rack: { asset: "dilution_tube_rack", label: "1.5 mL Tubes", role: "decoration", scene: "hood" },
	waste_container: { asset: "waste_container", label: "Waste", role: "waste_target", scene: "hood" },
	biohazard_decant: { asset: "biohazard_decant", label: "Biohazard", role: "waste_target", scene: "hood" },
	centrifuge: { asset: "centrifuge", label: "Centrifuge", role: "instrument", scene: "bench" },
	water_bath: { asset: "water_bath", label: "37C Water Bath", role: "instrument", scene: "bench" },
	cell_counter: { asset: "cell_counter", label: "Cell Counter", role: "instrument", scene: "bench" },
	microscope: { asset: "microscope", label: "Microscope", role: "instrument", scene: "bench" },
	vortex: { asset: "vortex", label: "Vortex", role: "instrument", scene: "bench", visualOnly: true },
	incubator: { asset: "incubator", label: "Incubator", role: "instrument", scene: "bench" },
	plate_reader: { asset: "plate_reader", label: "Plate Reader", role: "instrument", scene: "bench", visualOnly: true },
	hood_surface: { label: "Hood work surface", role: "virtual_target", scene: "virtual", visualOnly: true },
	professor: { asset: "angry_professor", label: "Professor", role: "decoration", scene: "overlay", visualOnly: true },
};

export const REAGENTS: Record<string, InventoryReagent> = {
	media: { colorKey: "media", displayColor: "#f7a6b8", label: "Complete media" },
	pbs: { colorKey: "pbs", displayColor: "#b8e5ff", label: "1x PBS" },
	trypsin: { colorKey: "trypsin", displayColor: "#ffe082", label: "Trypsin-EDTA" },
	cells: { colorKey: "cells", displayColor: "#f3d6a2", label: "Cell suspension" },
	drug: { colorKey: "drug", displayColor: "#d8b4ff", label: "Drug working stock" },
	mtt: { colorKey: "mtt", displayColor: "#fff59d", label: "MTT reagent" },
	dmso: { colorKey: "dmso", displayColor: "#e0e0e0", label: "DMSO" },
	ethanol: { colorKey: "ethanol", displayColor: "#ffd700", label: "70% Ethanol" },
	water: { colorKey: "water", displayColor: "#e8f4f8", label: "Sterile Water" },
	carboplatin: { colorKey: "carboplatin", displayColor: "#d0b0ff", label: "Carboplatin" },
	metformin: { colorKey: "metformin", displayColor: "#b0e0ff", label: "Metformin" },
};
