// AUTO-GENERATED by tools/build_protocol_data.py from content/tutorial_plate_intro/*.yaml. DO NOT EDIT BY HAND.

export interface InventoryItem {
	label: string;
	role: string;
	scene: string;
	asset?: string;
	liquidCapable?: boolean;
	capacityMl?: number;
	allowedLiquids?: string[];
	contains?: string;
	containsAny?: string[];
	visualOnly?: boolean;
}

export interface InventoryReagent {
	label: string;
	colorKey: string;
	displayColor: string;
}

export const EQUIPMENT: Record<string, InventoryItem> = {
	well_plate: { allowedLiquids: [ "carboplatin", "media" ], asset: "well_plate_96", capacityMl: 1, label: "96-Well Plate", liquidCapable: true, role: "culture_vessel", scene: "hood" },
	multichannel_pipette: { allowedLiquids: [ "carboplatin" ], asset: "multichannel_pipette", capacityMl: 300, label: "Multichannel pipette", liquidCapable: true, role: "transfer_tool", scene: "hood" },
	carboplatin_working_stock: { allowedLiquids: [ "carboplatin" ], asset: "dilution_tube_rack", capacityMl: 1.5, contains: "carboplatin", label: "Carboplatin 400 nM working stock", liquidCapable: true, role: "reagent_source", scene: "hood" },
};

export const REAGENTS: Record<string, InventoryReagent> = {
	carboplatin: { colorKey: "carboplatin", displayColor: "#d0b0ff", label: "Carboplatin" },
	media: { colorKey: "media", displayColor: "#f7a6b8", label: "Complete media" },
};
