// AUTO-GENERATED by tools/build_protocol_data.py from content/tutorial_plate_intro/*.yaml. DO NOT EDIT BY HAND.

import type { ProtocolStep } from "../constants";


export const PROTOCOL_ID = "tutorial_plate_intro";

export interface ProtocolPart {
	id: string;
	label: string;
	dayId: string;
}

export interface ProtocolDay {
	id: string;
	label: string;
}

export const PROTOCOL_STEPS: readonly ProtocolStep[] = [
	{
		action: "Click the 96-well plate to focus on it",
		completionPath: { advanceClick: "confirm-plate-intro", completionEvent: "tutorial-plate-opened", kind: "modal", openClick: "well_plate" },
		completionTrigger: { completionEvent: "click:tutorial-plate-opened", scene: "hood" },
		dayId: "tutorial_plate_day",
		errorHints: { not_loaded: "Click the 96-well plate to enter the plate workspace." },
		id: "tutorial_plate_open",
		label: "Open the 96-well plate workspace",
		modal: { owner: "plate", screen: "plate_intro" },
		nextId: "tutorial_plate_action",
		partId: "tutorial_plate_part",
		requiredItems: [ "well_plate" ],
		scene: "hood",
		stepIndex: 1,
		why: "Drug additions are easier to see when the plate is the whole scene.",
		usedItems: [],
	},
	{
		action: "Use the multichannel pipette to add 5 uL of the 400 nM Carboplatin working stock to row B, columns 1-12",
		completionPath: { advanceClick: "submit-plate-action", completionEvent: "tutorial-plate-submitted", kind: "modal", openClick: "well_plate" },
		completionTrigger: { completionEvent: "click:tutorial-plate-submitted", scene: "hood" },
		dayId: "tutorial_plate_day",
		errorHints: { incomplete: "Click the highlighted Add button to apply carboplatin to row B." },
		id: "tutorial_plate_action",
		label: "Add Carboplatin working stock to row B (10 nM)",
		modal: { owner: "plate", screen: "plate_add_carb_row_b" },
		nextId: null,
		partId: "tutorial_plate_part",
		requiredItems: [ "well_plate", "multichannel_pipette", "carboplatin_working_stock" ],
		scene: "hood",
		stepIndex: 2,
		why: "Mirrors OVCAR8 protocol Part 3 Day 2: 5 uL of carboplatin working stock per well across rows B-H. Row B (10 nM) is the lowest dose.",
		usedItems: [],
	},
];

export const PROTOCOL_PARTS: Record<string, ProtocolPart> = {
	tutorial_plate_part: { dayId: "tutorial_plate_day", id: "tutorial_plate_part", label: "Tutorial: 96-Well Plate Workspace" },
};

export const PROTOCOL_DAYS: Record<string, ProtocolDay> = {
	tutorial_plate_day: { id: "tutorial_plate_day", label: "Tutorial Day" },
};
