#!/usr/bin/env python3
"""
build_protocol_data.py - Compile protocol YAML to TypeScript data exports.

Reads content/<protocol>/items.yaml, content/<protocol>/reagents.yaml, and
content/<protocol>/protocol.yaml, validates them, and emits generated/protocol_data.ts
and generated/inventory_data.ts.
"""

import sys
import subprocess
import argparse
import pathlib
import re

import yaml


def get_repo_root() -> pathlib.Path:
	"""
	Determine REPO_ROOT via git rev-parse --show-toplevel.

	Raises:
		RuntimeError: If git command fails.

	Returns:
		Path to the repository root.
	"""
	result = subprocess.run(
		['git', 'rev-parse', '--show-toplevel'],
		capture_output=True,
		text=True,
	)
	if result.returncode != 0:
		raise RuntimeError(f"Failed to find repo root: {result.stderr}")
	return pathlib.Path(result.stdout.strip())


def load_yaml_file(path):
	"""
	Load a YAML file and return parsed content.

	Args:
		path: Path to the YAML file.

	Returns:
		Parsed YAML content as a dictionary.
	"""
	with open(path, 'r') as f:
		return yaml.safe_load(f)


def validate_items(items, repo_root, reagents):
	"""
	Validate all items in inventory.

	Returns set of all item ids that have assets (for later SVG check).
	Raises on validation failure.
	"""
	required_roles = {
		'transfer_tool', 'aspirate_tool', 'reagent_source',
		'culture_vessel', 'cell_container', 'waste_target',
		'instrument', 'modal_tool', 'virtual_target', 'decoration'
	}
	required_scenes = {'hood', 'bench', 'overlay', 'virtual', 'none'}
	reagent_ids = set(reagents.keys())

	items_with_assets = set()

	for item_id, item_def in items.items():
		# Check required fields
		if not isinstance(item_def, dict):
			raise ValueError(f"Item '{item_id}': not a dict")
		if 'label' not in item_def:
			raise ValueError(f"Item '{item_id}': missing 'label'")
		if 'role' not in item_def:
			raise ValueError(f"Item '{item_id}': missing 'role'")
		if 'scene' not in item_def:
			raise ValueError(f"Item '{item_id}': missing 'scene'")

		# Validate role
		role = item_def['role']
		if role not in required_roles:
			raise ValueError(
				f"Item '{item_id}': role '{role}' not in {required_roles}"
			)

		# Validate scene
		scene = item_def['scene']
		if scene not in required_scenes:
			raise ValueError(
				f"Item '{item_id}': scene '{scene}' not in {required_scenes}"
			)

		# If scene is not virtual/none, asset is required
		if scene not in ('virtual', 'none'):
			if 'asset' not in item_def:
				raise ValueError(f"Item '{item_id}': asset required for scene '{scene}'")
			items_with_assets.add(item_id)
			# Note: some items are procedurally generated and may not have
			# physical SVG files in assets/equipment/, which is OK.
			# Examples: pbs_bottle, trypsin_bottle are generated by svg_assets.ts.

		# Validate liquidCapable items have capacityMl and allowedLiquids
		if item_def.get('liquidCapable'):
			if 'capacityMl' not in item_def:
				raise ValueError(
					f"Item '{item_id}': liquidCapable=true but missing capacityMl"
				)
			if 'allowedLiquids' not in item_def:
				raise ValueError(
					f"Item '{item_id}': liquidCapable=true but missing allowedLiquids"
				)
			# Validate allowedLiquids references valid reagents
			for liquid_id in item_def['allowedLiquids']:
				if liquid_id not in reagent_ids:
					raise ValueError(
						f"Item '{item_id}': allowedLiquids references unknown reagent '{liquid_id}'"
					)

		# Validate reagent_source items have contains or containsAny
		if role == 'reagent_source':
			if 'contains' not in item_def and 'containsAny' not in item_def:
				raise ValueError(
					f"Item '{item_id}': reagent_source but no 'contains' or 'containsAny'"
				)
			# Validate contains references valid reagent
			if 'contains' in item_def:
				if item_def['contains'] not in reagent_ids:
					raise ValueError(
						f"Item '{item_id}': contains references unknown reagent '{item_def['contains']}'"
					)
			# Validate containsAny references valid reagents
			if 'containsAny' in item_def:
				for liquid_id in item_def['containsAny']:
					if liquid_id not in reagent_ids:
						raise ValueError(
							f"Item '{item_id}': containsAny references unknown reagent '{liquid_id}'"
						)

	return items_with_assets


def validate_reagents(reagents):
	"""Validate all reagents in inventory. Raises on validation failure."""
	for reagent_id, reagent_def in reagents.items():
		if not isinstance(reagent_def, dict):
			raise ValueError(f"Reagent '{reagent_id}': not a dict")
		if 'label' not in reagent_def:
			raise ValueError(f"Reagent '{reagent_id}': missing 'label'")
		if 'colorKey' not in reagent_def:
			raise ValueError(f"Reagent '{reagent_id}': missing 'colorKey'")
		if 'displayColor' not in reagent_def:
			raise ValueError(f"Reagent '{reagent_id}': missing 'displayColor'")


#============================================
# Completion path parsing (SP-K2a)
#============================================

def parse_completion_path(step, items, reagents):
	"""
	Parse the completionPath field from a step's YAML.

	If no completionPath is present, returns None (legacy path is used).
	If completionPath is present, parses it according to its kind discriminator
	and returns a dict suitable for emitting to TypeScript.

	Raises ValueError on invalid kind or missing required fields.
	"""
	if 'completionPath' not in step:
		return None

	cp = step['completionPath']
	if not isinstance(cp, dict):
		raise ValueError(f"Step '{step['id']}': completionPath must be a dict")

	if 'kind' not in cp:
		raise ValueError(f"Step '{step['id']}': completionPath missing 'kind'")

	kind = cp['kind']

	if kind == 'interactionSequence':
		if 'interactions' not in cp:
			raise ValueError(f"Step '{step['id']}': completionPath with kind 'interactionSequence' missing 'interactions'")
		interactions = cp['interactions']
		if not isinstance(interactions, list):
			raise ValueError(f"Step '{step['id']}': completionPath.interactions must be a list")
		return {
			'kind': 'interactionSequence',
			'interactions': interactions,
		}

	elif kind == 'directTool':
		if 'tool' not in cp:
			raise ValueError(f"Step '{step['id']}': completionPath with kind 'directTool' missing 'tool'")
		if 'completionEvent' not in cp:
			raise ValueError(f"Step '{step['id']}': completionPath with kind 'directTool' missing 'completionEvent'")
		return {
			'kind': 'directTool',
			'tool': cp['tool'],
			'completionEvent': cp['completionEvent'],
		}

	elif kind == 'modal':
		# openClick is optional: if omitted, the modal is assumed to be already open
		# from the previous step's completionEvent (for split hybrid steps).
		if 'advanceClick' not in cp:
			raise ValueError(f"Step '{step['id']}': completionPath with kind 'modal' missing 'advanceClick'")
		if 'completionEvent' not in cp:
			raise ValueError(f"Step '{step['id']}': completionPath with kind 'modal' missing 'completionEvent'")
		result = {
			'kind': 'modal',
			'advanceClick': cp['advanceClick'],
			'completionEvent': cp['completionEvent'],
		}
		# Only include openClick if it's present and non-empty
		if 'openClick' in cp and cp['openClick']:
			result['openClick'] = cp['openClick']
		return result

	else:
		raise ValueError(f"Step '{step['id']}': completionPath kind '{kind}' not in ['interactionSequence', 'directTool', 'modal']")


#============================================


def derive_used_items(step):
	"""
	Derive the list of items used in a step by walking interactionSequence.

	For each interaction, appends ids in order: tool, source, destination.
	First occurrence wins (de-duplication). Missing fields are skipped.
	Returns a list of de-duplicated item ids.
	"""
	used = []
	seen = set()

	interactions = step.get('interactionSequence', [])
	for interaction in interactions:
		# Append in inner order: tool, source, destination
		for field in ['tool', 'source', 'destination']:
			item_id = interaction.get(field)
			if item_id and item_id not in seen:
				used.append(item_id)
				seen.add(item_id)

	return used


#============================================


def validate_no_discharge_without_load(step, items):
	"""
	Rule 1: Discharge interaction with liquid set but no preceding load
	with matching tool and liquid.

	Raises ValueError on violation.
	"""
	step_id = step['id']
	interactions = step.get('interactionSequence', [])

	# Build a map of (tool, liquid) -> interaction index for all load interactions
	loads = {}
	for idx, interaction in enumerate(interactions):
		if 'source' in interaction and 'liquid' in interaction and 'destination' not in interaction:
			# This is a load interaction
			tool = interaction.get('tool')
			liquid = interaction.get('liquid')
			loads[(tool, liquid)] = idx

	# Check discharge interactions
	for idx, interaction in enumerate(interactions):
		if 'destination' in interaction and 'liquid' in interaction and 'source' not in interaction:
			# This is a discharge interaction
			tool = interaction.get('tool')
			liquid = interaction.get('liquid')
			if (tool, liquid) not in loads or loads[(tool, liquid)] >= idx:
				raise ValueError(
					f"Step '{step_id}' interaction {idx}: discharge with liquid '{liquid}' "
					f"has no preceding load with matching tool '{tool}'."
				)


#============================================


def validate_volume_sanity(step, items):
	"""
	Rule 2: Volume sanity violation (consumesVolumeMl exceeds the matching
	load's volumeMl).

	Raises ValueError on violation.
	"""
	step_id = step['id']
	interactions = step.get('interactionSequence', [])

	# Build a map of (tool, liquid) -> volumeMl for all load interactions
	loads = {}
	for idx, interaction in enumerate(interactions):
		if 'source' in interaction and 'liquid' in interaction:
			tool = interaction.get('tool')
			liquid = interaction.get('liquid')
			volume_ml = interaction.get('volumeMl')
			if volume_ml:
				loads[(tool, liquid)] = volume_ml

	# Check discharge interactions for consumesVolumeMl
	for idx, interaction in enumerate(interactions):
		if 'destination' in interaction and 'liquid' in interaction:
			tool = interaction.get('tool')
			liquid = interaction.get('liquid')
			consumes = interaction.get('consumesVolumeMl')
			if consumes:
				load_volume = loads.get((tool, liquid))
				if load_volume and consumes > load_volume:
					raise ValueError(
						f"Step '{step_id}' interaction {idx}: consumesVolumeMl {consumes} "
						f"exceeds load volumeMl {load_volume} for tool '{tool}' liquid '{liquid}'."
					)


#============================================


def validate_item_reagent_references(step, items, reagents):
	"""
	Rule 3: Interaction referencing items/reagents not in items.yaml/reagents.yaml.

	Validates that all tool, source, destination, and liquid fields in interactionSequence
	reference items/reagents that exist in the provided items and reagents dicts.

	Raises ValueError on violation.
	"""
	step_id = step['id']
	item_ids = set(items.keys())
	reagent_ids = set(reagents.keys())

	interactions = step.get('interactionSequence', [])
	for idx, interaction in enumerate(interactions):
		# Validate tool exists
		if 'tool' in interaction:
			tool = interaction['tool']
			if tool not in item_ids:
				raise ValueError(
					f"Step '{step_id}': interactionSequence[{idx}] tool '{tool}' not in inventory"
				)

		# Validate source exists if present
		if 'source' in interaction:
			source = interaction['source']
			if source not in item_ids:
				raise ValueError(
					f"Step '{step_id}': interactionSequence[{idx}] source '{source}' not in inventory"
				)

		# Validate destination exists if present
		if 'destination' in interaction:
			destination = interaction['destination']
			if destination not in item_ids:
				raise ValueError(
					f"Step '{step_id}': interactionSequence[{idx}] destination '{destination}' not in inventory"
				)

		# Validate liquid exists if present
		if 'liquid' in interaction:
			liquid = interaction['liquid']
			if liquid not in reagent_ids:
				raise ValueError(
					f"Step '{step_id}': interactionSequence[{idx}] liquid '{liquid}' not in reagents"
				)


#============================================


def validate_completion_event_placement(step):
	"""
	Rule 4: Completion-event placement:
	- More than one interaction with completionEvent, OR
	- The only completionEvent is not on the final interaction.

	Raises ValueError on violation.
	"""
	step_id = step['id']
	interactions = step.get('interactionSequence', [])

	completion_indices = []
	for idx, interaction in enumerate(interactions):
		if 'completionEvent' in interaction:
			completion_indices.append(idx)

	if len(completion_indices) > 1:
		raise ValueError(
			f"Step '{step_id}': more than one interaction has completionEvent."
		)

	if completion_indices:
		final_idx = len(interactions) - 1
		if completion_indices[0] != final_idx:
			raise ValueError(
				f"Step '{step_id}': completionEvent is not on the final interaction."
			)


#============================================


def validate_tool_first(step):
	"""
	Rule 5: Tool-first violation:
	Any interaction that has source, destination, liquid, or stateChange
	must declare tool. Exception: direct: true (allowed for items like
	opening an incubator door).

	Raises ValueError on violation.
	"""
	step_id = step['id']
	interactions = step.get('interactionSequence', [])

	for idx, interaction in enumerate(interactions):
		has_tool = 'tool' in interaction
		is_direct = interaction.get('direct', False)
		has_complex_field = (
			'source' in interaction or
			'destination' in interaction or
			'liquid' in interaction or
			'stateChange' in interaction
		)

		if has_complex_field and not has_tool and not is_direct:
			raise ValueError(
				f"Step '{step_id}' interaction {idx}: interaction has source/destination/liquid/stateChange "
				f"but no tool and direct is not true."
			)


#============================================


def validate_no_legacy_fields(step):
	"""
	Rule 6: Legacy field present in author YAML
	(actor/target/result/event/trigger/allowedInteractions/targetItems/requiredAction).

	Note: the banned field is bare `trigger`, NOT `completionTrigger` which is the
	new canonical step-level listener. Raises ValueError on violation.
	"""
	step_id = step['id']
	legacy_fields = {
		'actor', 'target', 'result', 'event', 'trigger',
		'allowedInteractions', 'targetItems', 'requiredAction'
	}

	found_legacy = legacy_fields & set(step.keys())
	if found_legacy:
		raise ValueError(
			f"Step '{step_id}': contains legacy fields: {found_legacy}. "
			f"Please remove: {', '.join(sorted(found_legacy))}."
		)


#============================================


def validate_no_virtual_target_destinations(step, items):
	"""
	Rule 7: virtual_target items must not be used as interaction.destination.

	Walks every interaction in the step's interactionSequence, looks up each
	destination in items, and raises if the destination item has role virtual_target.

	Use a direct tool interaction (tool + completionEvent, no destination) instead.

	Raises ValueError on violation.
	"""
	step_id = step['id']
	interactions = step.get('interactionSequence', [])

	for idx, interaction in enumerate(interactions):
		if 'destination' not in interaction:
			continue

		destination = interaction['destination']
		if destination not in items:
			# This should be caught by Rule 3, so skip here
			continue

		dest_item = items[destination]
		dest_role = dest_item.get('role')

		if dest_role == 'virtual_target':
			raise ValueError(
				f"Step '{step_id}' interaction {idx}: destination '{destination}' "
				f"has role 'virtual_target' and cannot be used as a click target. "
				f"Use a direct tool interaction (tool + completionEvent, no destination) instead."
			)


#============================================


def validate_completion_path_contract(step, items, reagents):
	"""
	Rule 8: Enforce the completionPath contract.

	Validates:
	(a) completionPath is required on every step
	(b) completionPath.kind is one of: interactionSequence, directTool, modal
	(c) For kind: interactionSequence:
	    - interactions is a non-empty list
	    - Banned fields: tool, openClick, advanceClick, completionEvent at kind-block level
	(d) For kind: directTool:
	    - tool is a non-empty string and resolves to items.yaml
	    - completionEvent is a non-empty string (no 'click:' prefix)
	    - Banned fields: interactions, openClick, advanceClick
	(e) For kind: modal:
	    - openClick is a non-empty string and resolves to items.yaml
	    - advanceClick is a non-empty kebab-case string (regex: ^[a-z][a-z0-9-]*$)
	    - completionEvent is a non-empty string (no 'click:' prefix)
	    - Banned fields: interactions, tool
	(f) Reject legacy top-level interactionSequence field
	(g) Reject author-written completionTrigger and targetItems (derived fields)

	Raises ValueError on violation.
	"""
	step_id = step['id']
	item_ids = set(items.keys())

	# (a) completionPath is required
	if 'completionPath' not in step:
		raise ValueError(
			f"Step '{step_id}': missing required completionPath block"
		)

	cp = step['completionPath']
	if not isinstance(cp, dict):
		raise ValueError(f"Step '{step_id}': completionPath must be a dict")

	# (b) kind must be one of the three allowed values
	if 'kind' not in cp:
		raise ValueError(f"Step '{step_id}': completionPath missing 'kind'")

	kind = cp['kind']
	allowed_kinds = {'interactionSequence', 'directTool', 'modal'}
	if kind not in allowed_kinds:
		raise ValueError(
			f"Step '{step_id}': completionPath kind '{kind}' not in {allowed_kinds}"
		)

	# (c) For kind: interactionSequence
	if kind == 'interactionSequence':
		if 'interactions' not in cp:
			raise ValueError(
				f"Step '{step_id}': completionPath kind 'interactionSequence' missing 'interactions'"
			)
		interactions = cp['interactions']
		if not isinstance(interactions, list) or len(interactions) == 0:
			raise ValueError(
				f"Step '{step_id}': completionPath.interactions must be a non-empty list"
			)
		# Check banned fields at kind-block level
		banned_at_kind = {'tool', 'openClick', 'advanceClick', 'completionEvent'}
		found_banned = banned_at_kind & set(cp.keys())
		if found_banned:
			raise ValueError(
				f"Step '{step_id}': completionPath kind 'interactionSequence' has banned fields: {found_banned}"
			)
		# Validate interactions with existing rules
		validate_step_interactions(step, items, reagents)

	# (d) For kind: directTool
	elif kind == 'directTool':
		if 'tool' not in cp or not cp['tool']:
			raise ValueError(
				f"Step '{step_id}': completionPath kind 'directTool' missing or empty 'tool'"
			)
		tool = cp['tool']
		if tool not in item_ids:
			raise ValueError(
				f"Step '{step_id}': completionPath.tool '{tool}' not in inventory"
			)
		if 'completionEvent' not in cp or not cp['completionEvent']:
			raise ValueError(
				f"Step '{step_id}': completionPath kind 'directTool' missing or empty 'completionEvent'"
			)
		completion_event = cp['completionEvent']
		if completion_event.startswith('click:'):
			raise ValueError(
				f"Step '{step_id}': completionPath.completionEvent '{completion_event}' must not start with 'click:'"
			)
		# Check banned fields
		banned_at_kind = {'interactions', 'openClick', 'advanceClick'}
		found_banned = banned_at_kind & set(cp.keys())
		if found_banned:
			raise ValueError(
				f"Step '{step_id}': completionPath kind 'directTool' has banned fields: {found_banned}"
			)

	# (e) For kind: modal
	elif kind == 'modal':
		# openClick is optional: if omitted, the modal is assumed to be already open
		# from the previous step's completionEvent (for split hybrid steps).
		if 'openClick' in cp and cp['openClick']:
			open_click = cp['openClick']
			if open_click not in item_ids:
				raise ValueError(
					f"Step '{step_id}': completionPath.openClick '{open_click}' not in inventory"
				)
		if 'advanceClick' not in cp or not cp['advanceClick']:
			raise ValueError(
				f"Step '{step_id}': completionPath kind 'modal' missing or empty 'advanceClick'"
			)
		advance_click = cp['advanceClick']
		# Validate advanceClick is kebab-case
		kebab_pattern = r'^[a-z][a-z0-9-]*$'
		if not re.match(kebab_pattern, advance_click):
			raise ValueError(
				f"Step '{step_id}': completionPath.advanceClick '{advance_click}' must be kebab-case (^[a-z][a-z0-9-]*$)"
			)
		if 'completionEvent' not in cp or not cp['completionEvent']:
			raise ValueError(
				f"Step '{step_id}': completionPath kind 'modal' missing or empty 'completionEvent'"
			)
		completion_event = cp['completionEvent']
		if completion_event.startswith('click:'):
			raise ValueError(
				f"Step '{step_id}': completionPath.completionEvent '{completion_event}' must not start with 'click:'"
			)
		# Check banned fields
		banned_at_kind = {'interactions', 'tool'}
		found_banned = banned_at_kind & set(cp.keys())
		if found_banned:
			raise ValueError(
				f"Step '{step_id}': completionPath kind 'modal' has banned fields: {found_banned}"
			)

	# (f) Reject legacy top-level interactionSequence
	if 'interactionSequence' in step:
		raise ValueError(
			f"Step '{step_id}': legacy top-level `interactionSequence` field is not allowed; move under completionPath"
		)

	# (g) Reject author-written completionTrigger and targetItems
	if 'completionTrigger' in step:
		raise ValueError(
			f"Step '{step_id}': `completionTrigger` is build-derived; do not author"
		)
	if 'targetItems' in step:
		raise ValueError(
			f"Step '{step_id}': `targetItems` is build-derived (`usedItems`); do not author"
		)


def validate_step_interactions(step, items, reagents):
	"""
	Validate step interactions against all seven rules.

	Raises on any violation with a clear message naming the step id and rule.
	"""
	# Rule 1: No discharge without preceding load
	validate_no_discharge_without_load(step, items)

	# Rule 2: Volume sanity
	validate_volume_sanity(step, items)

	# Rule 3: Item/reagent references (already validated in validate_steps)
	validate_item_reagent_references(step, items, reagents)

	# Rule 4: Completion event placement
	validate_completion_event_placement(step)

	# Rule 5: Tool-first
	validate_tool_first(step)

	# Rule 6: No legacy fields
	validate_no_legacy_fields(step)

	# Rule 7: virtual_target as destination forbidden
	validate_no_virtual_target_destinations(step, items)


#============================================


def validate_steps(steps, items, reagents, parts, days):
	"""
	Validate all protocol steps.

	Delegates to validate_step_interactions(step, items, reagents) which
	enumerates the seven validation rules: (1) no discharge without load,
	(2) volume sanity, (3) item/reagent references, (4) completion-event
	placement, (5) tool-first, (6) no legacy fields, (7) no virtual_target
	destinations. Raises ValueError on any violation.
	"""
	part_ids = {p['id'] for p in parts}
	day_ids = {d['id'] for d in days}
	item_ids = set(items.keys())
	reagent_ids = set(reagents.keys())
	valid_modal_owners = {'drug_treatment', 'microscope', 'incubator', 'plate', 'plate_reader'}

	valid_scenes = {'hood', 'bench', 'incubator', 'microscope', 'plate', 'plate_reader'}

	step_ids = set()
	first_step_id = None

	for i, step in enumerate(steps):
		if not isinstance(step, dict):
			raise ValueError(f"Step {i}: not a dict")

		step_id = step.get('id')
		if not step_id:
			raise ValueError(f"Step {i}: missing 'id'")
		if step_id in step_ids:
			raise ValueError(f"Step {i}: duplicate id '{step_id}'")
		step_ids.add(step_id)

		if first_step_id is None:
			first_step_id = step_id

		# Check required fields
		required = ['label', 'action', 'why', 'partId', 'dayId', 'stepIndex',
				'requiredItems', 'scene', 'nextId']
		for field in required:
			if field not in step:
				raise ValueError(f"Step '{step_id}': missing '{field}'")

		# Validate IDs reference valid parts/days
		part_id = step['partId']
		if part_id not in part_ids:
			raise ValueError(f"Step '{step_id}': partId '{part_id}' not found")
		day_id = step['dayId']
		if day_id not in day_ids:
			raise ValueError(f"Step '{step_id}': dayId '{day_id}' not found")

		# Validate scene
		scene = step['scene']
		if scene not in valid_scenes:
			raise ValueError(f"Step '{step_id}': scene '{scene}' not in {valid_scenes}")

		# Validate requiredItems exist
		for item_id in step['requiredItems']:
			if item_id not in item_ids:
				raise ValueError(
					f"Step '{step_id}': requiredItem '{item_id}' not in inventory"
				)

		# Validate modal field if present
		if 'modal' in step:
			modal = step['modal']
			if not isinstance(modal, dict):
				raise ValueError(f"Step '{step_id}': modal must be a dict")
			if 'owner' not in modal:
				raise ValueError(f"Step '{step_id}': modal missing 'owner'")
			if 'screen' not in modal:
				raise ValueError(f"Step '{step_id}': modal missing 'screen'")
			owner = modal['owner']
			if owner not in valid_modal_owners:
				raise ValueError(
					f"Step '{step_id}': modal.owner '{owner}' not in {valid_modal_owners}"
				)

		# Rule 8: Validate completionPath contract (SP-K2c)
		validate_completion_path_contract(step, items, reagents)

		# Validate interactionSequence field if present (for legacy/hybrid steps)
		if 'interactionSequence' in step:
			interactions = step['interactionSequence']
			if not isinstance(interactions, list):
				raise ValueError(f"Step '{step_id}': interactionSequence must be a list")
			for idx, interaction in enumerate(interactions):
				if not isinstance(interaction, dict):
					raise ValueError(
						f"Step '{step_id}': interactionSequence[{idx}] is not a dict"
					)
				# Validate tool field exists
				if 'tool' not in interaction:
					raise ValueError(
						f"Step '{step_id}': interactionSequence[{idx}] missing 'tool'"
					)
				tool = interaction['tool']
				if tool not in item_ids:
					raise ValueError(
						f"Step '{step_id}': interactionSequence[{idx}] tool '{tool}' not in inventory"
					)
				# Validate source exists if present
				if 'source' in interaction:
					source = interaction['source']
					if source not in item_ids:
						raise ValueError(
							f"Step '{step_id}': interactionSequence[{idx}] source '{source}' not in inventory"
						)
					source_item = items[source]
					source_role = source_item.get('role')
					valid_source_roles = {'reagent_source', 'cell_container', 'culture_vessel'}
					if source_role not in valid_source_roles:
						raise ValueError(
							f"Step '{step_id}': interactionSequence[{idx}] source '{source}' has role '{source_role}', expected one of {valid_source_roles}"
						)
				# Validate destination exists if present
				if 'destination' in interaction:
					destination = interaction['destination']
					if destination not in item_ids:
						raise ValueError(
							f"Step '{step_id}': interactionSequence[{idx}] destination '{destination}' not in inventory"
						)
					destination_item = items[destination]
					destination_role = destination_item.get('role')
					valid_destination_roles = {'cell_container', 'culture_vessel', 'waste_target', 'virtual_target', 'instrument'}
					if destination_role not in valid_destination_roles:
						raise ValueError(
							f"Step '{step_id}': interactionSequence[{idx}] destination '{destination}' has role '{destination_role}', expected one of {valid_destination_roles}"
						)
				# Validate liquid exists if present
				if 'liquid' in interaction:
					liquid = interaction['liquid']
					if liquid not in reagent_ids:
						raise ValueError(
							f"Step '{step_id}': interactionSequence[{idx}] liquid '{liquid}' not in reagents"
						)
					# Validate that the tool allows this liquid
					tool_item = items[tool]
					if tool_item.get('liquidCapable'):
						allowed_liquids = tool_item.get('allowedLiquids', [])
						if liquid not in allowed_liquids:
							raise ValueError(
								f"Step '{step_id}': interactionSequence[{idx}] tool '{tool}' does not allow liquid '{liquid}'"
							)
					# Validate that source contains this liquid if source is present
					if 'source' in interaction:
						source_item = items[interaction['source']]
						source_contains = source_item.get('contains')
						source_contains_any = source_item.get('containsAny', [])
						if source_contains and source_contains != liquid:
							raise ValueError(
								f"Step '{step_id}': interactionSequence[{idx}] source '{interaction['source']}' contains '{source_contains}', not '{liquid}'"
							)
						if source_contains_any and liquid not in source_contains_any:
							if not source_contains or source_contains != liquid:
								raise ValueError(
									f"Step '{step_id}': interactionSequence[{idx}] source '{interaction['source']}' does not contain '{liquid}'"
								)
				# Validate volumeMl if present
				if 'volumeMl' in interaction:
					volume_ml = interaction['volumeMl']
					tool_item = items[tool]
					if tool_item.get('liquidCapable'):
						capacity = tool_item.get('capacityMl', 0)
						if volume_ml > capacity:
							raise ValueError(
								f"Step '{step_id}': interactionSequence[{idx}] volumeMl {volume_ml} exceeds tool '{tool}' capacity {capacity}"
							)
				# Validate completionEvent matches completionTrigger if both present
				if 'completionEvent' in interaction and 'completionTrigger' in step:
					trigger_event = step['completionTrigger'].get('completionEvent', '')
					# Strip prefixes like 'click:' and 'modal_ok:'
					trigger_event_stripped = trigger_event.split(':', 1)[-1] if ':' in trigger_event else trigger_event
					interaction_event = interaction['completionEvent']
					if interaction_event != trigger_event_stripped:
						raise ValueError(
							f"Step '{step_id}': interactionSequence[{idx}] completionEvent '{interaction_event}' does not match completionTrigger event '{trigger_event_stripped}'"
						)

		# Validate step interactions against all six rules
		validate_step_interactions(step, items, reagents)

	# Check nextId chain
	if not first_step_id:
		raise ValueError("No steps defined")

	visited = set()
	current_id = first_step_id
	steps_by_id = {s['id']: s for s in steps}

	while current_id is not None:
		if current_id not in steps_by_id:
			raise ValueError(f"nextId chain: step '{current_id}' not found")
		if current_id in visited:
			raise ValueError(f"nextId chain: cycle detected at '{current_id}'")
		visited.add(current_id)

		step = steps_by_id[current_id]
		next_id = step.get('nextId')
		if next_id is None:
			# Final step
			break
		current_id = next_id

	# Check that all steps are visited
	if len(visited) != len(steps):
		missing = set(steps_by_id.keys()) - visited
		raise ValueError(f"nextId chain: orphaned steps: {missing}")

	# Exactly one terminator (nextId is null)
	terminators = [s for s in steps if s.get('nextId') is None]
	if len(terminators) != 1:
		raise ValueError(f"Expected 1 terminator, found {len(terminators)}")


def ts_escape_string(s):
	"""Escape a string for TypeScript."""
	s = s.replace('\\', '\\\\')
	s = s.replace('"', '\\"')
	s = s.replace('\n', '\\n')
	s = s.replace('\r', '\\r')
	s = s.replace('\t', '\\t')
	return s


def to_ts_value(value):
	"""Convert a Python value to TypeScript literal."""
	if value is None:
		return 'null'
	elif isinstance(value, bool):
		return 'true' if value else 'false'
	elif isinstance(value, (int, float)):
		return str(value)
	elif isinstance(value, str):
		return f'"{ts_escape_string(value)}"'
	elif isinstance(value, dict):
		if not value:
			return '{}'
		items = []
		for k, v in sorted(value.items()):
			items.append(f'{k}: {to_ts_value(v)}')
		return '{ ' + ', '.join(items) + ' }'
	elif isinstance(value, list):
		if not value:
			return '[]'
		items = [to_ts_value(v) for v in value]
		return '[ ' + ', '.join(items) + ' ]'
	else:
		raise ValueError(f"Unsupported type for TS: {type(value)}")


def object_to_ts_literal(obj):
	"""Convert a dict to TypeScript object literal."""
	if not obj:
		return '{}'
	items = []
	for key, value in sorted(obj.items()):
		items.append(f'{key}: {to_ts_value(value)}')
	return '{ ' + ', '.join(items) + ' }'


def discover_protocols(repo_root):
	"""Discover available protocols by globbing src/content/*/protocol.yaml."""
	content_dir = repo_root / 'src' / 'content'
	if not content_dir.is_dir():
		return []

	protocols = []
	for subdir in content_dir.iterdir():
		if subdir.is_dir():
			protocol_yaml = subdir / 'protocol.yaml'
			if protocol_yaml.exists():
				protocols.append(subdir.name)

	return sorted(protocols)


#============================================

PROTOCOL_METADATA = {
	'cell_culture': {
		'title': 'Cell Culture Protocol',
		'description': 'Complete the full split, count, seed, drug treatment, MTT, and plate read workflow.',
		'kind': 'full_protocol',
	},
	'tutorial_bench_direct': {
		'title': 'Bench Direct Tutorial',
		'description': 'Complete a simple one-click bench action.',
		'kind': 'tutorial',
	},
	'tutorial_cell_counter': {
		'title': 'Cell Counter Tutorial',
		'description': 'Capture a cell count with the automated counter.',
		'kind': 'tutorial',
	},
	'tutorial_drug_dilution': {
		'title': 'Drug Dilution Tutorial',
		'description': 'Prepare a simple drug dilution.',
		'kind': 'tutorial',
	},
	'tutorial_hemocytometer_count': {
		'title': 'Hemocytometer Count Tutorial',
		'description': 'Practice manual count entry.',
		'kind': 'tutorial',
	},
	'tutorial_hood_transfer': {
		'title': 'Hood Transfer Tutorial',
		'description': 'Move liquid safely in the hood.',
		'kind': 'tutorial',
	},
	'tutorial_pbs': {
		'title': 'PBS Tutorial',
		'description': 'Practice a repeat pipette transfer.',
		'kind': 'tutorial',
	},
	'tutorial_plate_intro': {
		'title': 'Plate Intro Tutorial',
		'description': 'Learn the plate workspace.',
		'kind': 'tutorial',
	},
	'tutorial_plate_reader': {
		'title': 'Plate Reader Tutorial',
		'description': 'Read an assay plate.',
		'kind': 'tutorial',
	},
	'tutorial_split': {
		'title': 'Split Tutorial',
		'description': 'Practice the first split workflow.',
		'kind': 'tutorial',
	},
}


def derive_protocol_title(protocol_name):
	"""Derive a readable protocol title from a protocol id."""
	if protocol_name == 'cell_culture':
		return 'Cell Culture Protocol'
	name = protocol_name
	if name.startswith('tutorial_'):
		name = name[len('tutorial_'):]
	words = name.split('_')
	title = ' '.join(word.upper() if word == 'pbs' else word.capitalize() for word in words)
	if protocol_name.startswith('tutorial_'):
		title += ' Tutorial'
	return title


def get_protocol_metadata(protocol_name, step_count):
	"""Return user-facing launcher metadata for a protocol."""
	metadata = PROTOCOL_METADATA.get(protocol_name, {})
	kind = metadata.get('kind')
	if kind is None:
		kind = 'tutorial' if protocol_name.startswith('tutorial_') else 'full_protocol'
	result = {
		'id': protocol_name,
		'title': metadata.get('title', derive_protocol_title(protocol_name)),
		'kind': kind,
		'stepCount': step_count,
	}
	if metadata.get('description'):
		result['description'] = metadata['description']
	return result


def load_protocol_bundle(repo_root, protocol_name):
	"""Load, validate, and normalize one protocol's YAML bundle."""
	protocol_dir = repo_root / 'src' / 'content' / protocol_name
	if not protocol_dir.is_dir():
		raise FileNotFoundError(f"Protocol directory not found: {protocol_dir}")

	items_path = protocol_dir / 'items.yaml'
	reagents_path = protocol_dir / 'reagents.yaml'
	protocol_path = protocol_dir / 'protocol.yaml'

	for path in [items_path, reagents_path, protocol_path]:
		if not path.exists():
			raise FileNotFoundError(f"Missing file: {path}")

	items_data = load_yaml_file(items_path)
	reagents_data = load_yaml_file(reagents_path)
	protocol = load_yaml_file(protocol_path)

	items = items_data.get('items', {})
	reagents = reagents_data.get('reagents', {})
	parts = protocol.get('parts', [])
	days = protocol.get('days', [])
	steps = protocol.get('steps', [])

	validate_reagents(reagents)
	validate_items(items, repo_root, reagents)
	validate_steps(steps, items, reagents, parts, days)

	for step in steps:
		cp = parse_completion_path(step, items, reagents)
		if cp is not None:
			step['completionPath'] = cp

	for step in steps:
		if 'completionPath' not in step:
			continue
		cp = step['completionPath']
		kind = cp.get('kind')
		scene = step.get('scene')

		if kind == 'directTool':
			event = cp.get('completionEvent', '')
			step['completionTrigger'] = {
				'scene': scene,
				'completionEvent': f'click:{event}'
			}
		elif kind == 'modal':
			event = cp.get('completionEvent', '')
			step['completionTrigger'] = {
				'scene': scene,
				'completionEvent': f'click:{event}'
			}
		elif kind == 'interactionSequence':
			interactions = cp.get('interactions', [])
			final_event = None
			for interaction in interactions:
				if 'completionEvent' in interaction:
					final_event = interaction['completionEvent']
			if final_event:
				step['completionTrigger'] = {
					'scene': scene,
					'completionEvent': f'click:{final_event}'
				}

	return {
		'items': items,
		'reagents': reagents,
		'parts': parts,
		'days': days,
		'steps': steps,
		'summary': get_protocol_metadata(protocol_name, len(steps)),
	}


def build_protocol_catalog(repo_root, protocol_names):
	"""Load all requested protocol bundles keyed by protocol id."""
	catalog = {}
	for protocol_name in protocol_names:
		catalog[protocol_name] = load_protocol_bundle(repo_root, protocol_name)
	return catalog


def render_steps_ts(steps, indent):
	"""Render a protocol step list as TypeScript."""
	lines = [indent + '[']
	for step in steps:
		lines.append(indent + '\t{')
		for key in sorted(step.keys()):
			value = step[key]
			lines.append(f'{indent}\t\t{key}: {to_ts_value(value)},')
		used_items = derive_used_items(step)
		lines.append(f'{indent}\t\tusedItems: {to_ts_value(used_items)},')
		lines.append(indent + '\t},')
	lines.append(indent + ']')
	return lines


def generate_protocol_data(steps, parts, days, protocol_name='cell_culture'):
	"""Generate TypeScript code for protocol_data.ts."""
	lines = [
		f'// AUTO-GENERATED by tools/build_protocol_data.py from content/{protocol_name}/*.yaml. DO NOT EDIT BY HAND.',
		'',
		'import type { ProtocolStep } from "../src/constants";',
		'',
		'',
		f'export const PROTOCOL_ID = "{protocol_name}";',
		'',
		'export interface ProtocolPart {',
		'\tid: string;',
		'\tlabel: string;',
		'\tdayId: string;',
		'}',
		'',
		'export interface ProtocolDay {',
		'\tid: string;',
		'\tlabel: string;',
		'}',
		'',
	]

	# Export PROTOCOL_STEPS
	lines.append('export const PROTOCOL_STEPS: readonly ProtocolStep[] = [')
	for step in steps:
		lines.append('\t{')
		for key in sorted(step.keys()):
			value = step[key]
			lines.append(f'\t\t{key}: {to_ts_value(value)},')
		# Append derived usedItems
		used_items = derive_used_items(step)
		lines.append(f'\t\tusedItems: {to_ts_value(used_items)},')
		lines.append('\t},')
	lines.append('];')
	lines.append('')

	# Export PROTOCOL_PARTS
	lines.append('export const PROTOCOL_PARTS: Record<string, ProtocolPart> = {')
	for part in parts:
		part_id = part['id']
		lines.append(f'\t{part_id}: {object_to_ts_literal(part)},')
	lines.append('};')
	lines.append('')

	# Export PROTOCOL_DAYS
	lines.append('export const PROTOCOL_DAYS: Record<string, ProtocolDay> = {')
	for day in days:
		day_id = day['id']
		lines.append(f'\t{day_id}: {object_to_ts_literal(day)},')
	lines.append('};')
	lines.append('')

	return '\n'.join(lines)


def generate_protocol_catalog_data(protocol_catalog, default_protocol='cell_culture'):
	"""Generate TypeScript code for a catalog-backed protocol_data.ts."""
	lines = [
		'// AUTO-GENERATED by tools/build_protocol_data.py from all src/content/*/*.yaml. DO NOT EDIT BY HAND.',
		'',
		'import type { ProtocolStep } from "../src/constants";',
		'',
		'export interface ProtocolPart {',
		'\tid: string;',
		'\tlabel: string;',
		'\tdayId: string;',
		'}',
		'',
		'export interface ProtocolDay {',
		'\tid: string;',
		'\tlabel: string;',
		'}',
		'',
		'export interface ProtocolSummary {',
		'\tid: string;',
		'\ttitle: string;',
		'\tkind: "full_protocol" | "tutorial";',
		'\tstepCount: number;',
		'\tdescription?: string;',
		'}',
		'',
		'export interface ProtocolCatalogEntry {',
		'\tsummary: ProtocolSummary;',
		'\tsteps: readonly ProtocolStep[];',
		'\tparts: Record<string, ProtocolPart>;',
		'\tdays: Record<string, ProtocolDay>;',
		'}',
		'',
	]

	lines.append('export const PROTOCOL_IDS = [')
	for protocol_name in sorted(protocol_catalog.keys()):
		lines.append(f'\t"{protocol_name}",')
	lines.append('] as const;')
	lines.append('')
	lines.append('export type ProtocolId = typeof PROTOCOL_IDS[number];')
	lines.append('')
	lines.append('const PROTOCOL_ID_SET: ReadonlySet<string> = new Set<string>(PROTOCOL_IDS);')
	lines.append('')

	lines.append('export const PROTOCOL_CATALOG: Record<ProtocolId, ProtocolCatalogEntry> = {')
	for protocol_name in sorted(protocol_catalog.keys()):
		bundle = protocol_catalog[protocol_name]
		lines.append(f'\t{protocol_name}: {{')
		lines.append(f'\t\tsummary: {object_to_ts_literal(bundle["summary"])},')
		lines.append('\t\tsteps: ' + render_steps_ts(bundle['steps'], '\t\t')[0].strip())
		for step_line in render_steps_ts(bundle['steps'], '\t\t')[1:]:
			lines.append(step_line)
		lines[-1] = lines[-1] + ','
		lines.append('\t\tparts: {')
		for part in bundle['parts']:
			part_id = part['id']
			lines.append(f'\t\t\t{part_id}: {object_to_ts_literal(part)},')
		lines.append('\t\t},')
		lines.append('\t\tdays: {')
		for day in bundle['days']:
			day_id = day['id']
			lines.append(f'\t\t\t{day_id}: {object_to_ts_literal(day)},')
		lines.append('\t\t},')
		lines.append('\t},')
	lines.append('};')
	lines.append('')

	lines.extend([
		'export function getRequestedProtocolId(): string | null {',
		'\tif (typeof window === "undefined") return null;',
		'\tconst params = new URLSearchParams(window.location.search);',
		'\treturn params.get("protocol");',
		'}',
		'',
		'export function isKnownProtocolId(value: string | null): value is ProtocolId {',
		'\tif (value === null) return false;',
		'\treturn PROTOCOL_ID_SET.has(value);',
		'}',
		'',
		f'export const DEFAULT_PROTOCOL_ID: ProtocolId = "{default_protocol}";',
		'export const REQUESTED_PROTOCOL_ID = getRequestedProtocolId();',
		'export const HAS_REQUESTED_PROTOCOL = REQUESTED_PROTOCOL_ID !== null;',
		'export const SELECTED_PROTOCOL_ID: ProtocolId | null = isKnownProtocolId(REQUESTED_PROTOCOL_ID)',
		'\t? REQUESTED_PROTOCOL_ID',
		'\t: null;',
		'export const REQUESTED_PROTOCOL_IS_VALID = SELECTED_PROTOCOL_ID !== null;',
		'export const INVALID_REQUESTED_PROTOCOL_ID: string | null =',
		'\tHAS_REQUESTED_PROTOCOL && !REQUESTED_PROTOCOL_IS_VALID',
		'\t\t? REQUESTED_PROTOCOL_ID',
		'\t\t: null;',
		'',
		'const ACTIVE_PROTOCOL_ID: ProtocolId = SELECTED_PROTOCOL_ID ?? DEFAULT_PROTOCOL_ID;',
		'export const PROTOCOL_ID: ProtocolId = ACTIVE_PROTOCOL_ID;',
		'export const PROTOCOL_STEPS: readonly ProtocolStep[] = PROTOCOL_CATALOG[ACTIVE_PROTOCOL_ID].steps;',
		'export const PROTOCOL_PARTS: Record<string, ProtocolPart> = PROTOCOL_CATALOG[ACTIVE_PROTOCOL_ID].parts;',
		'export const PROTOCOL_DAYS: Record<string, ProtocolDay> = PROTOCOL_CATALOG[ACTIVE_PROTOCOL_ID].days;',
		'export const PROTOCOL_SUMMARY: ProtocolSummary = PROTOCOL_CATALOG[ACTIVE_PROTOCOL_ID].summary;',
	])

	return '\n'.join(lines)


def generate_inventory_data(items, reagents, protocol_name='cell_culture'):
	"""Generate TypeScript code for inventory_data.ts."""
	lines = [
		f'// AUTO-GENERATED by tools/build_protocol_data.py from content/{protocol_name}/*.yaml. DO NOT EDIT BY HAND.',
		'',
		'export interface InventoryItem {',
		'\tlabel: string;',
		'\trole: string;',
		'\tscene: string;',
		'\tasset?: string;',
		'\tliquidCapable?: boolean;',
		'\tcapacityMl?: number;',
		'\tallowedLiquids?: string[];',
		'\tcontains?: string;',
		'\tcontainsAny?: string[];',
		'\tvisualOnly?: boolean;',
		'}',
		'',
		'export interface InventoryReagent {',
		'\tlabel: string;',
		'\tcolorKey: string;',
		'\tdisplayColor: string;',
		'}',
		'',
		'export const EQUIPMENT: Record<string, InventoryItem> = {',
	]

	for item_id, item_def in items.items():
		lines.append(f'\t{item_id}: {object_to_ts_literal(item_def)},')
	lines.append('};')
	lines.append('')

	lines.append('export const REAGENTS: Record<string, InventoryReagent> = {')
	for reagent_id, reagent_def in reagents.items():
		lines.append(f'\t{reagent_id}: {object_to_ts_literal(reagent_def)},')
	lines.append('};')
	lines.append('')

	return '\n'.join(lines)


def generate_inventory_catalog_data(protocol_catalog, default_protocol='cell_culture'):
	"""Generate TypeScript code for a catalog-backed inventory_data.ts."""
	lines = [
		'// AUTO-GENERATED by tools/build_protocol_data.py from all src/content/*/*.yaml. DO NOT EDIT BY HAND.',
		'',
		'import { DEFAULT_PROTOCOL_ID, SELECTED_PROTOCOL_ID, type ProtocolId } from "./protocol_data";',
		'',
		'export interface InventoryItem {',
		'\tlabel: string;',
		'\trole: string;',
		'\tscene: string;',
		'\tasset?: string;',
		'\tliquidCapable?: boolean;',
		'\tcapacityMl?: number;',
		'\tallowedLiquids?: string[];',
		'\tcontains?: string;',
		'\tcontainsAny?: string[];',
		'\tvisualOnly?: boolean;',
		'}',
		'',
		'export interface InventoryReagent {',
		'\tlabel: string;',
		'\tcolorKey: string;',
		'\tdisplayColor: string;',
		'}',
		'',
		'export interface InventoryCatalogEntry {',
		'\tequipment: Record<string, InventoryItem>;',
		'\treagents: Record<string, InventoryReagent>;',
		'}',
		'',
		'export const INVENTORY_CATALOG: Record<ProtocolId, InventoryCatalogEntry> = {',
	]

	for protocol_name in sorted(protocol_catalog.keys()):
		bundle = protocol_catalog[protocol_name]
		lines.append(f'\t{protocol_name}: {{')
		lines.append('\t\tequipment: {')
		for item_id, item_def in bundle['items'].items():
			lines.append(f'\t\t\t{item_id}: {object_to_ts_literal(item_def)},')
		lines.append('\t\t},')
		lines.append('\t\treagents: {')
		for reagent_id, reagent_def in bundle['reagents'].items():
			lines.append(f'\t\t\t{reagent_id}: {object_to_ts_literal(reagent_def)},')
		lines.append('\t\t},')
		lines.append('\t},')
	lines.append('};')
	lines.append('')
	lines.append('const ACTIVE_PROTOCOL_ID: ProtocolId = SELECTED_PROTOCOL_ID ?? DEFAULT_PROTOCOL_ID;')
	lines.append('export const EQUIPMENT: Record<string, InventoryItem> = INVENTORY_CATALOG[ACTIVE_PROTOCOL_ID].equipment;')
	lines.append('export const REAGENTS: Record<string, InventoryReagent> = INVENTORY_CATALOG[ACTIVE_PROTOCOL_ID].reagents;')

	return '\n'.join(lines)


def main():
	"""Main entry point."""
	parser = argparse.ArgumentParser(
		description='Compile protocol YAML to TypeScript data exports.'
	)
	group = parser.add_mutually_exclusive_group()
	group.add_argument(
		'-p', '--protocol',
		dest='protocol',
		default=None,
		help='Validate one protocol by name. Generated output still includes the full catalog.',
	)
	group.add_argument(
		'-l', '--list-protocols',
		dest='list_protocols',
		action='store_true',
		help='List available protocols and exit.',
	)
	parser.add_argument(
		'--validate-only',
		action='store_true',
		help='Validate only; do not regenerate output files.',
	)
	args = parser.parse_args()

	repo_root = get_repo_root()

	# Handle --list-protocols
	if args.list_protocols:
		protocols = discover_protocols(repo_root)
		for p in protocols:
			print(p)
		return 0

	if args.protocol is not None:
		protocol_names = [args.protocol]
	else:
		protocol_names = discover_protocols(repo_root)

	try:
		protocol_catalog = build_protocol_catalog(repo_root, protocol_names)
	except (FileNotFoundError, ValueError) as err:
		print(f"Error: {err}", file=sys.stderr)
		return 1

	if args.validate_only:
		print("Validation passed.")
		return 0

	full_catalog = build_protocol_catalog(repo_root, discover_protocols(repo_root))

	# Generate and write output files. Normal builds always emit the full catalog
	# so the browser can select protocols at runtime.
	protocol_data_ts = generate_protocol_catalog_data(full_catalog)
	inventory_data_ts = generate_inventory_catalog_data(full_catalog)

	# Both protocol_data.ts and inventory_data.ts are generated artifacts (gitignored under generated/)
	# The public facades are src/protocol.ts and src/inventory.ts
	protocol_data_path = repo_root / 'generated' / 'protocol_data.ts'
	inventory_data_path = repo_root / 'generated' / 'inventory_data.ts'

	# Ensure generated/ exists
	protocol_data_path.parent.mkdir(parents=True, exist_ok=True)

	with open(protocol_data_path, 'w') as f:
		f.write(protocol_data_ts)
	with open(inventory_data_path, 'w') as f:
		f.write(inventory_data_ts)
	print(f"Generated {protocol_data_path}")
	print(f"Generated {inventory_data_path}")

	return 0


if __name__ == '__main__':
	sys.exit(main())
