// tools/offcanvas_baseline.mjs
//
// Developer tool: generate the committed baseline of
// scenes currently flagged by the report-only per-item off-canvas classifier.
//
// It runs the layout engine once per scene at the canonical 16:9 frame (the same
// call pipeline/precompute_layout.mjs makes) and reads the report-only
// result.offCanvasDiagnostics stream. Each escaping item is graded
// fully_off_canvas (error class) or partial_overflow (warning, magnitude-scaled).
// The tool writes the flagged-scene list to:
//
//   docs/active_plans/audits/offcanvas_baseline.md
//
// REPORT-ONLY: this tool reads diagnostics and writes a Markdown audit. It never
// mutates layout, never writes to src/, generated/, or dist/, and never fails a
// build. The off-canvas diagnostic is intentionally not a build gate; promoting
// it is out of scope.
//
// Run:
//   node --import tsx tools/offcanvas_baseline.mjs

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

import { runPipeline } from "../src/scene_runtime/layout/index.ts";
import { SCENES } from "../generated/scenes.ts";
import { OBJECT_LIBRARY, ASSET_SPECS } from "../generated/object_library.ts";

// Canonical compiled-layout frame: matches pipeline/precompute_layout.mjs so the
// baseline reflects the exact positions the production build precomputes.
const BASELINE_VIEWPORT = { w: 1920, h: 1080 };

//============================================
// Repo root and output path
//============================================

// Resolve the repo root from git so the output path does not depend on cwd
// (repo style: never derive paths from the current working directory).
function repoRoot() {
  const top = execFileSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8" });
  return top.trim();
}

//============================================
// Per-scene off-canvas collection
//============================================

// Run the engine for one scene and return its report-only off-canvas findings.
function sceneOffCanvas(scene) {
  const result = runPipeline(scene, {
    library: OBJECT_LIBRARY,
    assets: ASSET_SPECS,
    viewport: BASELINE_VIEWPORT,
  });
  return result.offCanvasDiagnostics;
}

// Build the per-scene baseline records, sorted worst-first (most errors, then
// most total findings, then scene name). Only flagged scenes are returned.
function collectBaseline() {
  const sceneNames = Object.keys(SCENES).sort();
  const records = [];
  for (const name of sceneNames) {
    const findings = sceneOffCanvas(SCENES[name]);
    if (findings.length === 0) continue;
    const errors = findings.filter((f) => f.severity === "error");
    const warnings = findings.filter((f) => f.severity === "warning");
    records.push({
      scene: name,
      errorCount: errors.length,
      warningCount: warnings.length,
      total: findings.length,
      findings,
    });
  }
  records.sort((a, b) => {
    if (b.errorCount !== a.errorCount) return b.errorCount - a.errorCount;
    if (b.total !== a.total) return b.total - a.total;
    return a.scene < b.scene ? -1 : a.scene > b.scene ? 1 : 0;
  });
  return { sceneNames, records };
}

//============================================
// Markdown rendering
//============================================

function renderMarkdown(baseline) {
  const { sceneNames, records } = baseline;
  const totalScenes = sceneNames.length;
  const flaggedScenes = records.length;
  const totalErrors = records.reduce((s, r) => s + r.errorCount, 0);
  const totalWarnings = records.reduce((s, r) => s + r.warningCount, 0);

  const lines = [];
  lines.push("# Off-canvas validation baseline");
  lines.push("");
  lines.push(
    "Report-only per-item off-canvas classification. This " +
      "baseline is generated by `tools/offcanvas_baseline.mjs` from the layout " +
      "engine's report-only `offCanvasDiagnostics` stream at the canonical 16:9 " +
      "frame (" +
      BASELINE_VIEWPORT.w +
      "x" +
      BASELINE_VIEWPORT.h +
      ").",
  );
  lines.push("");
  lines.push(
    "The diagnostic only reports; it never fails or blocks a build. Each escaping " +
      "item is graded against `scene_bounds`:",
  );
  lines.push("");
  lines.push(
    "- `fully_off_canvas` (error class): the whole artwork box sits outside " +
      "`scene_bounds` (the object is invisible).",
  );
  lines.push(
    "- `partial_overflow` (warning): the box crosses a `scene_bounds` edge; the " +
      "warning magnitude scales with the worst-axis overshoot in scene-percent " +
      "(minor / moderate / severe tier).",
  );
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- scenes analyzed: ${totalScenes}`);
  lines.push(`- scenes flagged: ${flaggedScenes}`);
  lines.push(`- fully off-canvas items (error class): ${totalErrors}`);
  lines.push(`- partial-overflow items (warning): ${totalWarnings}`);
  lines.push("");

  if (flaggedScenes === 0) {
    lines.push("No scene currently has an off-canvas item. The baseline is empty.");
    lines.push("");
    return lines.join("\n");
  }

  // --- Flagged-scene roll-up ---
  lines.push("## Flagged scenes (worst first)");
  lines.push("");
  lines.push("| Scene | Fully off-canvas (error) | Partial overflow (warning) |");
  lines.push("| --- | --- | --- |");
  for (const r of records) {
    lines.push(`| ${r.scene} | ${r.errorCount} | ${r.warningCount} |`);
  }
  lines.push("");

  // --- Per-scene item detail ---
  lines.push("## Per-scene item detail");
  lines.push("");
  for (const r of records) {
    lines.push(`### ${r.scene}`);
    lines.push("");
    lines.push("| Item | Zone | Class | Severity | Worst overshoot (%) | Tier |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const f of r.findings) {
      lines.push(
        `| ${f.placementName} | ${f.zone} | ${f.classification} | ${f.severity} | ` +
          `${f.worstOverflow} | ${f.tier} |`,
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

//============================================
// Main
//============================================

function main() {
  const root = repoRoot();
  const outPath = path.join(root, "docs", "active_plans", "audits", "offcanvas_baseline.md");
  const baseline = collectBaseline();
  const text = renderMarkdown(baseline);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, text, "utf8");

  // Echo the flagged-scene list so the run log records coverage.
  const flagged = baseline.records.map((r) => r.scene);
  process.stdout.write(
    "offcanvas_baseline: analyzed " +
      baseline.sceneNames.length +
      " scenes, flagged " +
      flagged.length +
      "\n",
  );
  if (flagged.length > 0) {
    process.stdout.write("flagged scenes: " + flagged.join(", ") + "\n");
  }
  process.stdout.write("wrote: " + outPath + "\n");
}

main();
